const IMAGES = {
  Sun: {
    sunrise: require("./sunrise.svg").default,
    sunset: require("./sunset.svg").default,
  },
  Moon: {
    newMoon: require("./moon-new.svg").default,
    waxingCrescent: require("./moon-waxing-crescent.svg").default,
    firstQuarter: require("./moon-first-quarter.svg").default,
    waxingGibbous: require("./moon-waxing-gibbous.svg").default,
    full: require("./moon-full.svg").default,
    waningGibbous: require("./moon-waning-gibbous.svg").default,
    lastQuarter: require("./moon-last-quarter.svg").default,
    waningCrescent: require("./moon-waning-crescent.svg").default,
  },
  Index: [
    require("./uv-index-1.svg").default,
    require("./uv-index-2.svg").default,
    require("./uv-index-3.svg").default,
    require("./uv-index-4.svg").default,
    require("./uv-index-5.svg").default,
    require("./uv-index-6.svg").default,
    require("./uv-index-7.svg").default,
    require("./uv-index-8.svg").default,
    require("./uv-index-9.svg").default,
    require("./uv-index-10.svg").default,
    require("./uv-index-11.svg").default,
  ],
  Icon: {
    thunderstorms: require("./thunderstorms.svg").default,
    thunderstormsRain: require("./thunderstorms-rain.svg").default,
    drizzle: require("./drizzle.svg").default,
    rain: require("./rain.svg").default,
    sleet: require("./sleet.svg").default,
    snow: require("./snow.svg").default,
    snowflake: require("./snowflake.svg").default,
    mist: require("./mist.svg").default,
    smoke: require("./smoke.svg").default,
    haze: require("./haze.svg").default,
    dustWind: require("./dust-wind.svg").default,
    fog: require("./fog.svg").default,
    dust: require("./dust.svg").default,
    wind: require("./wind.svg").default,
    tornado: require("./tornado.svg").default,
    clearDay: require("./clear-day.svg").default,
    clearNight: require("./clear-night.svg").default,
    cloudy: require("./cloudy.svg").default,
    overcastDay: require("./overcast-day.svg").default,
    overcastNight: require("./overcast-night.svg").default,
    overcast: require("./overcast.svg").default,
  },
  Other: {
    raindrop: require("./raindrop.svg").default,
  },
};
export default IMAGES;
