const IMAGES = {
  Sun: {
    sunrise: require("./sunrise.svg"),
    sunset: require("./sunset.svg"),
  },
  Moon: {
    newMoon: require("./moon-new.svg"),
    waxingCrescent: require("./moon-waxing-crescent.svg"),
    firstQuarter: require("./moon-first-quarter.svg"),
    waxingGibbous: require("./moon-waxing-gibbous.svg"),
    full: require("./moon-full.svg"),
    waningGibbous: require("./moon-waning-gibbous.svg"),
    lastQuarter: require("./moon-last-quarter.svg"),
    waningCrescent: require("./moon-waning-crescent.svg"),
  },
  Index: [
    require("./uv-index-1.svg"),
    require("./uv-index-2.svg"),
    require("./uv-index-3.svg"),
    require("./uv-index-4.svg"),
    require("./uv-index-5.svg"),
    require("./uv-index-6.svg"),
    require("./uv-index-7.svg"),
    require("./uv-index-8.svg"),
    require("./uv-index-9.svg"),
    require("./uv-index-10.svg"),
    require("./uv-index-11.svg"),
  ],
  Icon: {
    thunderstorms: require("./thunderstorms.svg"),
    thunderstormsRain: require("./thunderstorms-rain.svg"),
    drizzle: require("./drizzle.svg"),
    rain: require("./rain.svg"),
    sleet: require("./sleet.svg"),
    snow: require("./snow.svg"),
    snowflake: require("./snowflake.svg"),
    mist: require("./mist.svg"),
    smoke: require("./smoke.svg"),
    haze: require("./haze.svg"),
    dustWind: require("./dust-wind.svg"),
    fog: require("./fog.svg"),
    dust: require("./dust.svg"),
    wind: require("./wind.svg"),
    tornado: require("./tornado.svg"),
    clearDay: require("./clear-day.svg"),
    clearNight: require("./clear-night.svg"),
    cloudy: require("./cloudy.svg"),
    overcastDay: require("./overcast-day.svg"),
    overcastNight: require("./overcast-night.svg"),
    overcast: require("./overcast.svg"),
  },
  Other: {
    raindrop: require("./raindrop.svg"),
  },
};
export default IMAGES;
